/*
Automatically generated by HaskellDirect (ihc.exe), version 0.20
Created: 20:11 Pacific Standard Time, Tuesday 16 December, 2003
Command line: -fno-qualified-names -fno-export-list -fno-gen-variant-instances -fout-pointers-are-not-refs --gen-headers -c StdTypes.idl -o StdTypes.hs
*/


#ifndef __INT64_DEFINED__
#ifdef __GNUC__
typedef long long int64;
typedef unsigned long long uint64;
#else
#ifdef _MSC_VER
typedef __int64 int64;
typedef unsigned __int64 uint64;
#else
/* Need some help here, please. */
#endif
#endif
#define __INT64_DEFINED__
#endif


#ifndef __STDTYPES_H__
#define __STDTYPES_H__
#ifdef __MINGW32__
#define __need_wchar_t
#include <stddef.h>
#endif
typedef unsigned long UINT;
typedef int INT;
typedef long BOOL;
typedef char BYTE;
typedef long LONG;
typedef unsigned long ULONG;
typedef unsigned short WORD;
typedef unsigned long DWORD;
typedef unsigned short VARTYPE;
typedef unsigned short USHORT;
typedef DWORD LCID;
typedef LONG SCODE;
typedef short SHORT;
typedef wchar_t WCHAR;
typedef WCHAR TCHAR;
typedef WCHAR OLECHAR;
typedef /*[string]*/ WCHAR* LPOLESTR;
typedef /*[string]*/ WCHAR* LPCOLESTR;
typedef void* PVOID;
typedef void* LPVOID;
typedef float FLOAT;
/*typedef [ignore] [ignore]struct _GUID {
                      [ignore]unsigned long Data1;
                      [ignore]unsigned short Data2;
                      [ignore]unsigned short Data3;
                      char [ignore] Data4[8];
                   } GUID;*/
typedef struct _GUID {
DWORD Data1;
WORD  Data2;
WORD  Data3;
BYTE  Data4[8];
} GUID;
/*typedef [ignore] GUID IID;*/
typedef GUID IID;
typedef IID* LPIID;
/*typedef [ignore] GUID CLSID;*/
typedef GUID CLSID;
typedef CLSID* LPCLSID;
typedef GUID FMTID;
typedef FMTID* LPFMTID;
typedef /*[ptr]*/ void* HWND;
typedef /*[ptr]*/ void* HMENU;
typedef /*[ptr]*/ void* HANDLE;
typedef /*[ref]*/ GUID* REFGUID;
typedef /*[ref]*/ IID* REFIID;
typedef /*[ref]*/ CLSID* REFCLSID;
typedef /*[ref]*/ FMTID* REFFMTID;
typedef enum VARENUM {
           VT_EMPTY = 0,
           VT_NULL = 1,
           VT_I2 = 2,
           VT_I4 = 3,
           VT_R4 = 4,
           VT_R8 = 5,
           VT_CY = 6,
           VT_DATE = 7,
           VT_BSTR = 8,
           VT_DISPATCH = 9,
           VT_ERROR = 10,
           VT_BOOL = 11,
           VT_VARIANT = 12,
           VT_UNKNOWN = 13,
           VT_DECIMAL = 14,
           VT_I1 = 16,
           VT_UI1 = 17,
           VT_UI2 = 18,
           VT_UI4 = 19,
           VT_I8 = 20,
           VT_UI8 = 21,
           VT_INT = 22,
           VT_UINT = 23,
           VT_VOID = 24,
           VT_HRESULT = 25,
           VT_PTR = 26,
           VT_SAFEARRAY = 27,
           VT_CARRAY = 28,
           VT_USERDEFINED = 29,
           VT_LPSTR = 30,
           VT_LPWSTR = 31,
           VT_FILETIME = 64,
           VT_BLOB = 65,
           VT_STREAM = 66,
           VT_STORAGE = 67,
           VT_STREAMED_OBJECT = 68,
           VT_STORED_OBJECT = 69,
           VT_BLOB_OBJECT = 70,
           VT_CF = 71,
           VT_CLSID = 72,
           VT_BSTR_BLOB = 4095,
           VT_ILLEGALMASKED = 4095,
           VT_TYPEMASK = 4095,
           VT_VECTOR = 4096,
           VT_ARRAY = 8192,
           VT_BYREF = 16384,
           VT_RESERVED = 32768,
           VT_ILLEGAL = 65535
        } VARENUM;

#endif
