module Math {

  [pure]int  abs([in]int x);
  [pure]long labs([in]long x);
  [pure]double fabs([in]double x);

  [pure]double ceil([in]double x);
  [pure]double floor([in]double x);
  [pure]double fmod([in]double x,[in]double y);

  [pure]double exp([in]double x);
  [pure]double log([in]double x);
  [pure]double log10([in]double x);

  [pure]double frexp([in]double x,[in,out,ref]int* nptr);
  [pure]double ldexp([in]double x,[in]int n);
  [pure]double modf([in]double x,[in,out,ref]double* nptr);

  [pure]double pow([in]double x,[in]double y);
  [pure]double sqrt([in]double x);

  [pure]int rand(void);
  void srand([in]int seed);
  
  [pure]double cos([in]double x);
  [pure]double sin([in]double x);
  [pure]double tan([in]double x);

  [pure]double acos([in]double x);
  [pure]double asin([in]double x);
  [pure]double atan([in]double x);
  [pure]double atan2([in]double x,
                     [in]double y);

  [pure]double cosh([in]double x);
  [pure]double sinh([in]double x);
  [pure]double tanh([in]double x);
};
